name: CI Pipeline

on:
    push:
        branches:
            - "main"
    pull_request:
        branches:
            - "main"

jobs:
    lint:
        uses: ./.github/workflows/lint.yml

    format:
        uses: ./.github/workflows/format.yml

    run-tests:
        uses: ./.github/workflows/tests.yml

    check-docstring:
        uses: ./.github/workflows/docstring-check.yml

    type-check:
        uses: ./.github/workflows/type-check.yml

    docker:
        uses: ./.github/workflows/docker.yml
